# fly.toml app configuration file generated for story-mapper-2316 on 2026-07-25T08:11:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'story-mapper-2316'
primary_region = 'lhr'

[build]
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
